# Generated by Django 5.2 on 2025-05-24 11:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                ("plan_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "plan_name",
                    models.CharField(
                        help_text="Name of the subscription plan", max_length=255
                    ),
                ),
                (
                    "plan_description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the plan",
                        null=True,
                    ),
                ),
                (
                    "plan_period",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                        ],
                        help_text="Billing period of the plan",
                        max_length=50,
                    ),
                ),
                (
                    "plan_tier",
                    models.CharField(
                        blank=True,
                        help_text="Tier level of the plan",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "plan_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Price of the plan",
                        max_digits=10,
                    ),
                ),
                (
                    "plan_currency",
                    models.CharField(
                        default="USD",
                        help_text="Currency for the plan price",
                        max_length=10,
                    ),
                ),
                (
                    "plan_duration_days",
                    models.IntegerField(
                        blank=True, help_text="Duration of the plan in days", null=True
                    ),
                ),
                (
                    "is_trial",
                    models.BooleanField(
                        default=False, help_text="Whether this is a trial plan"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the plan is currently active"
                    ),
                ),
                (
                    "meta_data",
                    models.JSONField(
                        blank=True,
                        help_text="Additional metadata for the plan",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Subscription Plan",
                "verbose_name_plural": "Subscription Plans",
                "ordering": ["plan_price"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="usage_plans_is_acti_d7e0b1_idx"
                    ),
                    models.Index(
                        fields=["plan_period"], name="usage_plans_plan_pe_598736_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PlanFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature_name",
                    models.CharField(help_text="Name of the feature", max_length=255),
                ),
                (
                    "feature_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of the feature",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "feature_description",
                    models.TextField(
                        blank=True, help_text="Description of the feature", null=True
                    ),
                ),
                (
                    "feature_limit",
                    models.IntegerField(
                        blank=True, help_text="Usage limit for the feature", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the feature is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="usage_plans.subscriptionplan",
                    ),
                ),
            ],
            options={
                "ordering": ["feature_name"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="usage_plans_is_acti_90b722_idx"
                    ),
                    models.Index(
                        fields=["feature_name"], name="usage_plans_feature_765fbb_idx"
                    ),
                ],
                "unique_together": {("plan", "feature_name")},
            },
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "subscription_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe subscription ID",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "usage_start_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Start date of subscription",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the subscription is active"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Whether the subscription is deleted"
                    ),
                ),
                (
                    "meta_data",
                    models.JSONField(
                        blank=True,
                        help_text="Additional metadata for the subscription",
                        null=True,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="usage_plans.subscriptionplan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Subscription",
                "verbose_name_plural": "User Subscriptions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="usage_plans_is_acti_53fce9_idx"
                    ),
                    models.Index(
                        fields=["user", "is_active"],
                        name="usage_plans_user_id_1ef92e_idx",
                    ),
                ],
            },
        ),
    ]
