# Generated by Django 5.2 on 2025-05-24 11:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("create_agent", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationCategory",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "category_name",
                    models.CharField(help_text="Name of the category", max_length=255),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of the category"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp of creation",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp of last update"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the category is active"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        help_text="The agent this integration category belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integration_categories",
                        to="create_agent.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Integration Category",
                "verbose_name_plural": "Integration Categories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Integration",
            fields=[
                ("integration_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "integration_name",
                    models.CharField(
                        help_text="Name of the integration", max_length=255
                    ),
                ),
                (
                    "integration_type",
                    models.CharField(
                        help_text="Type of integration (e.g., 'api', 'webhook', 'oauth')",
                        max_length=50,
                    ),
                ),
                (
                    "integration_url",
                    models.URLField(
                        blank=True,
                        help_text="URL endpoint for the integration",
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "integration_key",
                    models.CharField(
                        blank=True,
                        help_text="API key or access key",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "integration_secret",
                    models.CharField(
                        blank=True,
                        help_text="Secret key for authentication",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "integration_token",
                    models.CharField(
                        blank=True,
                        help_text="Access token for OAuth integrations",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of the integration"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp of creation",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp of last update"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the integration is active"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, help_text="Soft delete flag"),
                ),
                (
                    "is_archived",
                    models.BooleanField(default=False, help_text="Archive flag"),
                ),
                (
                    "configuration",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional configuration settings",
                    ),
                ),
                (
                    "meta_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional metadata"
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        help_text="The agent this integration belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrations",
                        to="create_agent.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Integration",
                "verbose_name_plural": "Integrations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["integration_type"],
                        name="integration_integra_a51a04_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="integration_is_acti_8c5c73_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="integration_created_ba9df0_idx"
                    ),
                ],
            },
        ),
    ]
